export const lettersPhotoMapping = {
    a: "./letterImages/0.jpg",
    b: "./letterImages/1.jpg",
    c: "./letterImages/2.jpg",
    d: "./letterImages/3.jpg",
    e: "./letterImages/4.jpg",
    f: "./letterImages/5.jpg",
    g: "./letterImages/6.jpg",
    h: "./letterImages/7.jpg",
    i: "./letterImages/8.jpg",
    j: "./letterImages/9.jpg",
    k: "./letterImages/10.jpg",
    l: "./letterImages/11.jpg",
    m: "./letterImages/12.jpg",
    n: "./letterImages/13.jpg",
    o: "./letterImages/14.jpg",
    p: "./letterImages/15.jpg",
    q: "./letterImages/16.jpg",
    r: "./letterImages/17.jpg",
    s: "./letterImages/18.jpg",
    t: "./letterImages/19.jpg",
    u: "./letterImages/20.jpg",
    v: "./letterImages/21.jpg",
    w: "./letterImages/22.jpg",
    x: "./letterImages/23.jpg",
    y: "./letterImages/24.jpg",
    z: "./letterImages/25.jpg",
    ' ': "./letterImages/space.jpg",
}