export const WordVideoMapping = {
    aeroplane : "./wordVideos/aeroplane.mp4",
    book : "./wordVideos/book.mp4",
    daughter : "./wordVideos/daughter.mp4",
    deaf : "./wordVideos/deaf.mp4",
    die : "./wordVideos/die.mp4",
    dog : "./wordVideos/dog.mp4",
    fan : "./wordVideos/fan.mp4",
    fish : "./wordVideos/fish.mp4",
    gun : "./wordVideos/gun.mp4",
    hat : "./wordVideos/hat.mp4",
    hello : "./wordVideos/hello.mp4",
    i : "./wordVideos/i.mp4",
    india : "./wordVideos/india.mp4",
    job : "./wordVideos/job.mp4",
    love : "./wordVideos/love.mp4",
    marry : "./wordVideos/marry.mp4",
    sad : "./wordVideos/sad.mp4",
    son : "./wordVideos/son.mp4",
    thankyou: "./wordVideos/thankyou.mp4",
    today : "./wordVideos/today.mp4",
    tomorrow : "./wordVideos/tomorrow.mp4",
    woman : "./wordVideos/woman.mp4",
    yesterday : "./wordVideos/yesterday.mp4",
    you : "./wordVideos/you.mp4",
}